ss:
  include:
    - . # paths to scan (default: entire repo)
  exclude:
    - tests/ # paths to skip
strict: true
strictness_threshold: HIGH
output:
  file_path: results-secret-scan.csv
  format: CSV