name: SECRET_SCAN
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 8 * * 1"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: fluidattacks/ss-action@0.2.0
        id: scan
        with:
          scanner_mode: full
          scan_config_path: .github/secret-scan-config.yaml

      - name: Upload Secret Scan CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fluid-attacks-secret-scan-csv
          path: .fluidattacks-secret-scan-results.csv

      - name: Fail if Secret Scan found vulnerabilities
        if: always() && steps.scan.outputs.vulnerabilities_found == 'true'
        run: exit 1